services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: foundly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

  migration:
    build:
      context: ./foundly
      dockerfile: Dockerfile
    container_name: django_migration
    command: >
      sh -c "python manage.py migrate --noinput"
    volumes:
      - ./foundly:/foundly
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: foundly
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_HOST: db
      DB_PORT: 5432
    restart: "no"

  django:
    build:
      context: ./foundly
      dockerfile: Dockerfile
    container_name: django_app
    restart: always
    volumes:
      - ./foundly:/foundly
      - ./media:/foundly/media
    ports:
      - "8000:8000"
    depends_on:
      migration:
        condition: service_completed_successfully
    environment:
      DB_NAME: foundly
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_HOST: db
      DB_PORT: 5432
    command: >
      sh -c "python manage.py migrate --noinput && python manage.py loaddata --exclude auth.permission --exclude contenttypes initial_data.json && daphne -b 0.0.0.0 -p 8000 foundly.asgi:application"
#      sh -c "python manage.py migrate --noinput && daphne -b 0.0.0.0 -p 8000 foundly.asgi:application"





volumes:
  pg_data: