# Generated by Django 5.1.7 on 2025-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
