# Generated by Django 5.1.4 on 2025-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brithday',
            field=models.DateField(max_length=20, unique=True),
        ),
    ]
