# Generated by Django 5.1.7 on 2025-04-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_subcategory_item_subsubcategory_item_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=1, upload_to='categories/'),
            preserve_default=False,
        ),
    ]
