# Generated by Django 5.1.4 on 2025-02-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_user_brithday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='brithday',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
