# Generated by Django 5.1.6 on 2025-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_user_brithday_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='media/profile_photo/photo_2025-02-24 23.37.57.jpeg', upload_to='media/profile_photo/'),
        ),
    ]
