# Generated by Django 5.2 on 2025-04-13 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemphoto',
            name='predicted_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.category'),
        ),
    ]
