# Generated by Django 5.1.6 on 2025-03-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemphoto',
            name='item',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_photo/photo_2025-02-24 23.37.57.jpeg', upload_to='profile_photo/'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemPhoto',
        ),
    ]
