# Generated by Django 5.1.7 on 2025-03-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_itemphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
